Update android.yml

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -34,15 +34,17 @@ jobs:
 
       - name: Check if port is in use and kill process
         run: |
+          set -e  # Exit immediately if any command fails
           PORT=4723  # Replace with the port number you want to check
-          PID=$(lsof -t -i:$PORT)
+          PID=$(lsof -t -i:$PORT || true)  # Use '|| true' to prevent script failure if lsof command fails
           if [ -n "$PID" ]; then
             echo "Process using port $PORT found. Killing process..."
-            kill $PID
+            kill $PID || true  # Use '|| true' to prevent script failure if kill command fails
             sleep 5  # Wait for the process to be killed
           else
             echo "Port $PORT is free."
           fi
+
           
       - name: Start Appium server
         run: appium -a 127.0.0.1 -p 4723 &
@@ -147,17 +149,19 @@ jobs:
           sleep 300
 
 
-      - name: Check if port is in use and kill process
-        run: |
-          PORT=4724  # Replace with the port number you want to check
-          PID=$(lsof -t -i:$PORT)
-          if [ -n "$PID" ]; then
-            echo "Process using port $PORT found. Killing process..."
-            kill $PID
-            sleep 5  # Wait for the process to be killed
-          else
-            echo "Port $PORT is free."
-          fi
+          - name: Check if port is in use and kill process
+            run: |
+              set -e  # Exit immediately if any command fails
+              PORT=4724  # Replace with the port number you want to check
+              PID=$(lsof -t -i:$PORT || true)  # Use '|| true' to prevent script failure if lsof command fails
+              if [ -n "$PID" ]; then
+                echo "Process using port $PORT found. Killing process..."
+                kill $PID || true  # Use '|| true' to prevent script failure if kill command fails
+                sleep 5  # Wait for the process to be killed
+              else
+                echo "Port $PORT is free."
+              fi
+
 
 
       - name: Start another Appium server
